### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by umapython** [Xcov19/registrations#9]
AttributeError: 'ModelRegistry' object has no attribute '_create_all'
'
sys:1: RuntimeWarning: coroutine 'MotorClient.start_mongo_collection' was never awaited
attached is the error file faced when i tried to run the application
[error.txt](https://github.com/Xcov19/registrations/files/7645965/error.txt)

**Comment by codecakes** [comment]
Provide steps that you followed to reproduce this issue.

**Comment by umapython** [comment]
i got code from https://github.com/Xcov19/registrations
if i run the code using "uvicorn main:app --reload" ,the following error got removed
sys:1: RuntimeWarning: coroutine 'MotorClient.start_mongo_collection' was never awaited
but still i am getting this "AttributeError: 'ModelRegistry' object has no attribute '_create_all' error

**Comment by umapython** [comment]
AttributeError: 'ModelRegistry' object has no attribute '_create_all'
this is the error i am getting now

**Comment by codecakes** [comment]
If you check the Readme file from where you got the code, it has a section "How to Run". Just follow the steps to run with docker and check if you are able to run it.

Btw, where did you find out how to run It using the command you have provided?

**Comment by umapython** [comment]
after installing docker
sudo apy-get update
sudo apt-get install docker.io
sudo systemctl start docker
sudo systemctl status docker
sudo systemctl enable docker

sudo apt install docker-compose
sudo docker ps

after the above commands i run docker-compose up 
![tes](https://user-images.githubusercontent.com/81124314/145883344-ec94db83-995a-42e8-8481-58b60f32062d.png)
got the same error

**Comment by codecakes** [comment]
@umapython interesting. what is the output of:
`python3 -m pip freeze | grep orm==`  ?

  Are you running inside any virtualenv?

**Comment by umapython** [comment]
Used to give installed modules: python3 -m pip freeze

no ,not in any virtualenv

**Comment by umapython** [comment]
aiosqlite==0.17.0
anyio==3.4.0
apt-clone==0.2.1
apturl==0.5.2
asgiref==3.4.1
asyncpg==0.25.0
attrs==19.3.0
backcall==0.2.0
backports.entry-points-selectable==1.1.0
beanie==1.8.0
beautifulsoup4==4.8.2
blinker==1.4
Brlapi==0.7.0
cached-property==1.5.1
certifi==2019.11.28
chardet==3.0.4
charset-normalizer==2.0.9
click==7.1.2
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
cryptography==2.8
cupshelpers==1.0
databases==0.5.3
dbus-python==1.2.16
decorator==5.1.0
defer==1.0.6
distlib==0.3.3
distro==1.4.0
Django==3.2.7
dnspython==2.1.0
docker==4.1.0
docker-compose==1.25.0
dockerpty==0.4.1
docopt==0.6.2
email-validator==1.1.3
entrypoints==0.3
fastapi==0.70.0
filelock==3.0.12
greenlet==1.1.2
grpcio==1.16.1
h11==0.12.0
h2==4.1.0
hpack==4.0.0
httplib2==0.14.0
httptools==0.2.0
hypercorn==0.12.0
hyperframe==6.0.1
idna==2.8
ifaddr==0.1.6
IMDbPY==6.8
importlib-metadata==1.5.0
ipython==7.30.1
itsdangerous==2.0.1
jedi==0.18.1
Jinja2==3.0.3
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
more-itertools==4.2.0
motor==2.5.1
multidict==5.2.0
nemo-emblems==5.0.0
netaddr==0.7.19
netifaces==0.10.4
nose==1.3.7
numpy==1.21.2
oauthlib==3.1.0
onboard==1.4.1
orjson==3.6.5
orm==0.3.1
packaging==20.3
PAM==0.4.2
pandas==1.3.4
parso==0.8.3
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
pipenv==2021.5.29
platformdirs==2.3.0
priority==2.0.0
prompt-toolkit==3.0.23
protobuf==3.6.1
psutil==5.5.1
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.2
pydantic==1.8.2
Pygments==2.10.0
PyGObject==3.36.0
PyICU==2.4.2
pyinotify==0.9.6
PyJWT==1.7.1
pymacaroons==0.13.0
pymongo==3.12.2
PyNaCl==1.3.0
pyparsing==2.4.6
pyparted==3.11.2
PyQt5==5.14.1
pyRFC3339==1.1
pyrsistent==0.15.5
python-apt==2.0.0+ubuntu0.20.4.6
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
python-dotenv==0.19.2
python-magic==0.4.16
python-multipart==0.0.5
python-xapp==2.2.1
python-xlib==0.23
pytz==2019.3
pyxattr==0.6.1
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.26.0
requests-file==1.4.3
requests-unixsocket==0.2.0
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.16.0
sip==4.19.21
six==1.14.0
sniffio==1.2.0
soupsieve==1.9.5
SQLAlchemy==1.4.27
sqlparse==0.4.2
starlette==0.16.0
systemd-python==234
texttable==1.6.2
tinycss2==1.0.2
tldextract==2.2.1
toml==0.10.2
traitlets==5.1.1
typesystem==0.3.1
typing-extensions==4.0.1
ubuntu-advantage-tools==27.4
ubuntu-drivers-common==0.0.0
ufw==0.36
ujson==4.3.0
Unidecode==1.1.1
urllib3==1.25.8
uvicorn==0.15.0
uvloop==0.16.0
virtualenv==20.8.0
virtualenv-clone==0.5.7
wadllib==1.3.3
watchgod==0.7
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.53.0
websockets==10.1
wsproto==1.0.0
xkit==0.0.0
yarl==1.7.2
youtube-dl==2021.4.26
zeroconf==0.24.4
zipp==1.0.0
got after running python3 -m pip freeze

**Comment by codecakes** [comment]
@umapython 
If you cross check here: https://github.com/Xcov19/registrations/blob/develop/requirements.txt
your version is wrong

> orm==0.3.1

Try setting up a new virtualenv and then following the READ setup again.

**Comment by codecakes** [comment]
@umapython if you retry these steps now, what happens?

> after installing docker sudo apy-get update sudo apt-get install docker.io sudo systemctl start docker sudo systemctl status docker sudo systemctl enable docker
> 
> sudo apt install docker-compose sudo docker ps
> 
> after the above commands i run docker-compose up ![tes](https://user-images.githubusercontent.com/81124314/145883344-ec94db83-995a-42e8-8481-58b60f32062d.png) got the same error
